
package org.openbox.sf5.wsmodel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpenboxSF5", targetNamespace = "http://wsmodel.sf5.openbox.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenboxSF5 {


    /**
     * 
     * @param inputSetting
     * @return
     *     returns long
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSetting", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.CreateSetting")
    @ResponseWrapper(localName = "createSettingResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.CreateSettingResponse")
    public long createSetting(
        @WebParam(name = "inputSetting", targetNamespace = "")
        Settings inputSetting)
        throws WSException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Transponders>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransponders", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTransponders")
    @ResponseWrapper(localName = "getTranspondersResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTranspondersResponse")
    public List<Transponders> getTransponders()
        throws WSException
    ;

    /**
     * 
     * @param inputFieldName
     * @param inputFieldValue
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Settings>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSettingsByArbitraryFilter", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingsByArbitraryFilter")
    @ResponseWrapper(localName = "getSettingsByArbitraryFilterResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingsByArbitraryFilterResponse")
    public List<Settings> getSettingsByArbitraryFilter(
        @WebParam(name = "inputFieldName", targetNamespace = "")
        String inputFieldName,
        @WebParam(name = "inputFieldValue", targetNamespace = "")
        String inputFieldValue)
        throws WSException
    ;

    /**
     * 
     * @param inputFieldName
     * @param inputFieldValue
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Transponders>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTranspondersByArbitraryFilter", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTranspondersByArbitraryFilter")
    @ResponseWrapper(localName = "getTranspondersByArbitraryFilterResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTranspondersByArbitraryFilterResponse")
    public List<Transponders> getTranspondersByArbitraryFilter(
        @WebParam(name = "inputFieldName", targetNamespace = "")
        String inputFieldName,
        @WebParam(name = "inputFieldValue", targetNamespace = "")
        String inputFieldValue)
        throws WSException
    ;

    /**
     * 
     * @param inputUser
     * @return
     *     returns long
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.CreateUserResponse")
    public long createUser(
        @WebParam(name = "inputUser", targetNamespace = "")
        Users inputUser)
        throws WSException
    ;

    /**
     * 
     * @param inputLogin
     * @return
     *     returns boolean
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ifSuchLoginExists", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.IfSuchLoginExists")
    @ResponseWrapper(localName = "ifSuchLoginExistsResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.IfSuchLoginExistsResponse")
    public boolean ifSuchLoginExists(
        @WebParam(name = "inputLogin", targetNamespace = "")
        String inputLogin)
        throws WSException
    ;

    /**
     * 
     * @param inputLogin
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Settings>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSettingsByUserLogin", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingsByUserLogin")
    @ResponseWrapper(localName = "getSettingsByUserLoginResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingsByUserLoginResponse")
    public List<Settings> getSettingsByUserLogin(
        @WebParam(name = "inputLogin", targetNamespace = "")
        String inputLogin)
        throws WSException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Satellites>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSatellites", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetAllSatellites")
    @ResponseWrapper(localName = "getAllSatellitesResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetAllSatellitesResponse")
    public List<Satellites> getAllSatellites()
        throws WSException
    ;

    /**
     * 
     * @param inputFieldName
     * @param inputFieldValue
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Satellites>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSatellitesByArbitraryFilter", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSatellitesByArbitraryFilter")
    @ResponseWrapper(localName = "getSatellitesByArbitraryFilterResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSatellitesByArbitraryFilterResponse")
    public List<Satellites> getSatellitesByArbitraryFilter(
        @WebParam(name = "inputFieldName", targetNamespace = "")
        String inputFieldName,
        @WebParam(name = "inputFieldValue", targetNamespace = "")
        String inputFieldValue)
        throws WSException
    ;

    /**
     * 
     * @param inputTransponderId
     * @return
     *     returns org.openbox.sf5.wsmodel.Transponders
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransponderById", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTransponderById")
    @ResponseWrapper(localName = "getTransponderByIdResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTransponderByIdResponse")
    public Transponders getTransponderById(
        @WebParam(name = "inputTransponderId", targetNamespace = "")
        long inputTransponderId)
        throws WSException
    ;

    /**
     * 
     * @param inputSatelliteId
     * @return
     *     returns org.openbox.sf5.wsmodel.Satellites
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSatelliteById", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSatelliteById")
    @ResponseWrapper(localName = "getSatelliteByIdResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSatelliteByIdResponse")
    public Satellites getSatelliteById(
        @WebParam(name = "inputSatelliteId", targetNamespace = "")
        long inputSatelliteId)
        throws WSException
    ;

    /**
     * 
     * @param inputSettingId
     * @return
     *     returns org.openbox.sf5.wsmodel.Settings
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSettingById", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingById")
    @ResponseWrapper(localName = "getSettingByIdResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetSettingByIdResponse")
    public Settings getSettingById(
        @WebParam(name = "inputSettingId", targetNamespace = "")
        long inputSettingId)
        throws WSException
    ;

    /**
     * 
     * @param inputSatId
     * @return
     *     returns java.util.List<org.openbox.sf5.wsmodel.Transponders>
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTranspondersBySatelliteId", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTranspondersBySatelliteId")
    @ResponseWrapper(localName = "getTranspondersBySatelliteIdResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetTranspondersBySatelliteIdResponse")
    public List<Transponders> getTranspondersBySatelliteId(
        @WebParam(name = "inputSatId", targetNamespace = "")
        long inputSatId)
        throws WSException
    ;

    /**
     * 
     * @param inputLogin
     * @return
     *     returns org.openbox.sf5.wsmodel.Users
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByLogin", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetUserByLogin")
    @ResponseWrapper(localName = "getUserByLoginResponse", targetNamespace = "http://wsmodel.sf5.openbox.org/", className = "org.openbox.sf5.wsmodel.GetUserByLoginResponse")
    public Users getUserByLogin(
        @WebParam(name = "inputLogin", targetNamespace = "")
        String inputLogin)
        throws WSException
    ;

}
