
package org.openbox.sf5.wsmodel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenboxSF5Service", targetNamespace = "http://wsmodel.sf5.openbox.org/", wsdlLocation = "http://localhost:8080/SF5Spring-test/jaxws/OpenboxSF5Service?wsdl")
public class OpenboxSF5Service
    extends Service
{

    private final static URL OPENBOXSF5SERVICE_WSDL_LOCATION;
    private final static WebServiceException OPENBOXSF5SERVICE_EXCEPTION;
    private final static QName OPENBOXSF5SERVICE_QNAME = new QName("http://wsmodel.sf5.openbox.org/", "OpenboxSF5Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SF5Spring-test/jaxws/OpenboxSF5Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENBOXSF5SERVICE_WSDL_LOCATION = url;
        OPENBOXSF5SERVICE_EXCEPTION = e;
    }

    public OpenboxSF5Service() {
        super(__getWsdlLocation(), OPENBOXSF5SERVICE_QNAME);
    }

    public OpenboxSF5Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENBOXSF5SERVICE_QNAME, features);
    }

    public OpenboxSF5Service(URL wsdlLocation) {
        super(wsdlLocation, OPENBOXSF5SERVICE_QNAME);
    }

    public OpenboxSF5Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENBOXSF5SERVICE_QNAME, features);
    }

    public OpenboxSF5Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenboxSF5Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenboxSF5
     */
    @WebEndpoint(name = "OpenboxSF5Port")
    public OpenboxSF5 getOpenboxSF5Port() {
        return super.getPort(new QName("http://wsmodel.sf5.openbox.org/", "OpenboxSF5Port"), OpenboxSF5.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenboxSF5
     */
    @WebEndpoint(name = "OpenboxSF5Port")
    public OpenboxSF5 getOpenboxSF5Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsmodel.sf5.openbox.org/", "OpenboxSF5Port"), OpenboxSF5.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENBOXSF5SERVICE_EXCEPTION!= null) {
            throw OPENBOXSF5SERVICE_EXCEPTION;
        }
        return OPENBOXSF5SERVICE_WSDL_LOCATION;
    }

}
