
package org.openbox.sf5.wsmodel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CheckVerifyFault", targetNamespace = "http://wsmodel.sf5.openbox.org/")
public class WSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.openbox.sf5.wsmodel.WSException
     */
    public WSException getFaultInfo() {
        return faultInfo;
    }

}
